name: fazakir
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.3.2
  get_it: ^8.0.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.5
  dartz: ^0.10.1
  smooth_page_indicator: ^1.2.0+3
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  intl: ^0.19.0
  geolocator: ^13.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^17.2.3
  flutter_timezone: ^3.0.1
  flutter_markdown: ^0.7.3+2
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.2
  wakelock_plus: ^1.2.8
  adhan: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/quran-images/
    - assets/images/
    - assets/icons/
    - assets/json/
    - assets/fonts/
    - assets/md/

  fonts:
    - family: Arabic
      fonts:
        - asset: assets/fonts/UthmanTN1Ver10.otf
