name: fazakir
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.0.13
  get_it: ^7.2.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  dio: ^4.0.4
  flutter_svg: ^1.0.3
  equatable: ^2.0.3
  dartz: ^0.10.1
  smooth_page_indicator: ^1.0.0+2
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  intl: ^0.17.0
  geolocator: ^8.2.0
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^9.4.0
  flutter_native_timezone: ^2.0.0
  flutter_markdown: ^0.6.9+1
  url_launcher: ^6.0.20
  package_info_plus: ^1.4.0
  wakelock: ^0.6.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
flutter_icons:
  image_path: "assets/images/logoicon.png"
  android: true
  ios: false

  flutter_lints: ^1.0.0
  freezed: ^1.1.1
  build_runner: ^2.1.5
  json_serializable: ^6.1.1
  hive_generator: ^1.1.1
  

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/quran-images/
    - assets/images/
    - assets/icons/
    - assets/json/
    - assets/fonts/
    - assets/md/


  fonts:
    - family: Arabic
      fonts:
        - asset: assets/fonts/UthmanTN1Ver10.otf
        