
name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          channel: 'stable'
          architecture: x64
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
      - run: flutter doctor
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle
